version: '3.1'

services:
  db:
    image: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: courseDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  php:
    build: "./php"
    ports:
      - 8001:8001
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
volumes:
  mysql-data: