version: '3.1'

services:
  db:
    # container_name: appDB
    image: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --init-file /data/application/init.sql
    # restart: always
    environment:
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/data/appl
  php:
    build: "./php"
    ports:
      - 8001:8001
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
volumes:
  mysql-data: